version: "3.5"

services:
  thru-time-postgres-preview:
    image: postgres:14
    container_name: thru-time-postgres-preview
    env_file:
      - .env
    environment:
      - POSTGRES_USER=$PREVIEW_POSTGRES_USER
      - POSTGRES_PASSWORD=$PREVIEW_POSTGRES_PASSWORD
      - POSTGRES_DB=$PREVIEW_POSTGRES_DB
    volumes:
      - ./database/preview-data:/var/lib/postgresql/data/
    ports:
      - $PREVIEW_POSTGRES_PORT:5432
    restart: always

  thru-time-api-preview:
    depends_on:
      - thru-time-postgres-preview
    container_name: thru-time-api-preview
    image: ghcr.io/mikkisguy/thru-time-api:preview
    labels:
      - com.centurylinklabs.watchtower.enable=true
    env_file:
      - .env
    environment:
      - EXPRESS_PORT=$PREVIEW_EXPRESS_PORT
      - POSTGRES_USER=$PREVIEW_POSTGRES_USER
      - POSTGRES_PASSWORD=$PREVIEW_POSTGRES_PASSWORD
      - POSTGRES_DB=$PREVIEW_POSTGRES_DB
      - SSL_CERT_PATH=$SSL_CERT_PATH
      - SSL_KEY_PATH=$SSL_KEY_PATH
    volumes:
      - $SSL_CERT_PATH:$SSL_CERT_PATH
      - $SSL_KEY_PATH:$SSL_KEY_PATH
    ports:
      - $PREVIEW_EXPRESS_PORT:$PREVIEW_EXPRESS_PORT
    restart: always

  thru-time-frontend-preview:
    image: ghcr.io/mikkisguy/thru-time-frontend:preview
    container_name: thru-time-frontend-preview
    depends_on:
      - thru-time-api-preview
    labels:
      - com.centurylinklabs.watchtower.enable=true
    env_file:
      - .env
    environment:
      - SSL_CERT_PATH=$SSL_CERT_PATH
      - SSL_KEY_PATH=$SSL_KEY_PATH
    volumes:
      - $SSL_CERT_PATH:$SSL_CERT_PATH
      - $SSL_KEY_PATH:$SSL_KEY_PATH
    ports:
      - $PREVIEW_REACT_PORT:443
    restart: always
