services:
  thru-time-postgres-preview:
    image: postgres:14
    container_name: thru-time-postgres-preview
    env_file:
      - .env
    environment:
      - POSTGRES_USER=$PREVIEW_POSTGRES_USER
      - POSTGRES_PASSWORD=$PREVIEW_POSTGRES_PASSWORD
      - POSTGRES_DB=$PREVIEW_POSTGRES_DB
    volumes:
      - ./database/preview-data:/var/lib/postgresql/data/
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - $PREVIEW_POSTGRES_PORT:5432
    restart: unless-stopped

  thru-time-api-preview:
    depends_on:
      - thru-time-postgres-preview
    container_name: thru-time-api-preview
    image: ghcr.io/mikkisguy/thru-time-api:preview
    labels:
      - com.centurylinklabs.watchtower.enable=true
    env_file:
      - .env
    environment:
      - NODE_ENV=preview
      - EXPRESS_PORT=$PREVIEW_EXPRESS_PORT
      - POSTGRES_HOST=thru-time-postgres-preview
      - POSTGRES_USER=$PREVIEW_POSTGRES_USER
      - POSTGRES_PASSWORD=$PREVIEW_POSTGRES_PASSWORD
      - POSTGRES_DB=$PREVIEW_POSTGRES_DB
      - POSTGRES_PORT=5432
      - SSL_CERT_PATH=$SSL_CERT_PATH
      - SSL_KEY_PATH=$SSL_KEY_PATH
      - SEED_DATA_USER=$SEED_DATA_USER
      - SEED_DATA_PASSWORD=$SEED_DATA_PASSWORD
    volumes:
      - $SSL_CERT_PATH:$SSL_CERT_PATH
      - $SSL_KEY_PATH:$SSL_KEY_PATH
    ports:
      - $PREVIEW_EXPRESS_PORT:$PREVIEW_EXPRESS_PORT
    restart: unless-stopped

  thru-time-frontend-preview:
    image: ghcr.io/mikkisguy/thru-time-frontend:preview
    container_name: thru-time-frontend-preview
    depends_on:
      - thru-time-api-preview
    labels:
      - com.centurylinklabs.watchtower.enable=true
    env_file:
      - .env
    environment:
      - SSL_CERT_PATH=$SSL_CERT_PATH
      - SSL_KEY_PATH=$SSL_KEY_PATH
    volumes:
      - $SSL_CERT_PATH:$SSL_CERT_PATH
      - $SSL_KEY_PATH:$SSL_KEY_PATH
    ports:
      - $PREVIEW_REACT_PORT:443
    restart: unless-stopped
