version: "3.5"

services:
  thru-time-postgres:
    image: postgres:14
    container_name: thru-time-postgres
    env_file:
      - .env
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    volumes:
      - ./database/data:/var/lib/postgresql/data/
    ports:
      - $POSTGRES_PORT:5432
    restart: always

  thru-time-api:
    depends_on:
      - thru-time-postgres
    container_name: thru-time-api
    image: ghcr.io/mikkisguy/thru-time-api:latest
    env_file:
      - .env
    environment:
      - EXPRESS_PORT=$EXPRESS_PORT
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
      - SSL_CERT_PATH=$SSL_CERT_PATH
      - SSL_KEY_PATH=$SSL_KEY_PATH
    volumes:
      - $SSL_CERT_PATH:$SSL_CERT_PATH
      - $SSL_KEY_PATH:$SSL_KEY_PATH
    ports:
      - $EXPRESS_PORT:$EXPRESS_PORT
    restart: always

  thru-time-frontend:
    image: ghcr.io/mikkisguy/thru-time-frontend:latest
    container_name: thru-time-frontend
    depends_on:
      - thru-time-api
    env_file:
      - .env
    environment:
      - VITE_API_URL=$VITE_API_URL
      - VITE_PREVIEW_SITE=false
    ports:
      - $REACT_PORT:443
    restart: always
